### ISSUE TITLE
glith

### ISSUE THREAD

**Issue by whisp1488** [EdwinS7/edwnGui#3]
I made dynamic link library, and menu flicked every time, how to fix?

**Comment by whisp1488** [comment]
> May I see your code? I did not encounter this problem when testing.

https://www.upload.ee/files/15265495/MenuSDK.rar.html

**Comment by yoka121337** [comment]
It was literally an executable build, was this just some config issue for vs or you forgot to build this as .dll?!

**Comment by yoka121337** [comment]
sent a video or a pic of ur menu inside csgo

**Comment by whisp1488** [comment]
> sent a video or a pic of ur menu inside csgo

https://streamable.com/4u7fnd

**Comment by yoka121337** [comment]
wasn't able to answer, glad you've fixed it
